version: "3"
services:
    elastic:
        image: "elasticsearch:7.14.2"
        env_file: 
            - ./.env_elastic
        environment:
            - "logger.level=WARN"
        ports:
            - 9200:9200
            - 9300:9300
        volumes:
            - ./data-es:/usr/share/elasticsearch/data:rw    
    # client:
    #     container_name: client
    #     build:
    #         context: ./client
    #         dockerfile: Dockerfile
    #     ports:
    #         - 8082:3000
