version: "3"
services:
    nginx:
        image: nginx:1.15-alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./data/nginx:/etc/nginx/conf.d
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot   
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    elastic:
        image: "elasticsearch:7.14.2"
        env_file: 
            - ./.env_elastic
        environment:
            - "logger.level=WARN"
            - "discovery.type=single-node"
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - 9200:9200
            - 9300:9300
        # volumes:
        #     - ./data-es:/usr/share/elasticsearch/data:rw
    nominatim:
        image: "mediagis/nominatim:3.7"
        env_file: 
            - ./.env_nominatim
        # ports:
        #     - "8081:8080"
        #     - "5431:5432"
        volumes:
            - ./data-osm/berkeley.osm.pbf:/nominatim/data/berkeley.osm.pbf
            # - ./status:/var/lib/postgresql/12/main
    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        environment:
            - "ES_HOST=elastic"
            - "ES_PORT=9200"
        volumes:
            - ./jars/api-0.0.1-SNAPSHOT.jar:/srv/api/app.jar
            - ./status:/srv/api/status
        ports:
            - "8080:8080"
    pg2es:
        build:
            context: ./pg2es
            dockerfile: Dockerfile
        environment:
            - "ES_HOST=elastic"
            - "ES_PORT=9200"
            - "PG_HOST=nominatim"
            - "PG_PORT=5432"
        volumes:
            - ./jars/pg2es-0.0.1-SNAPSHOT.jar:/srv/api/app.jar
            - ./pg2es/categories.csv:/srv/api/categories.csv
            - ./status:/var/tmp
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "8081:3000"
